healthstopwatchv2/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :medicines
  resources :stopwatches do
    collection do
      get 'change_watch1'
      get 'change_watch2'
      get 'change_watch3'
    end
  end
  root 'home#index'

end

healthstopwatchv2/app/models/medicine.rb
class Medicine < ActiveRecord::Base
  belongs_to :stopwatch
end

healthstopwatchv2/app/models/stopwatch.rb
class Stopwatch < ActiveRecord::Base
  has_many :medicines
end

healthstopwatchv2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

healthstopwatchv2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

healthstopwatchv2/app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:Name, :time)
    end
end

healthstopwatchv2/app/controllers/stopwatches_controller.rb
class StopwatchesController < ApplicationController
  before_action :set_stopwatch, only: [:show, :edit, :update, :destroy]

  # GET /stopwatches
  # GET /stopwatches.json
  def index
  @medicines = Medicine.all
   @string1 = "Hydromorphine 2 mg"
   @string2 = "Oxycodone 5 mg"
   @string3 = "Tramadol 50 mg"
   @time_1 = 0
   @time_2 = 0
   @time_3 = 0
   gon.myNum1 = @time_1
   gon.myNum2 = @time_2
   gon.myNum3 = @time_3
 end

 def change_watch1
   @string1 = "Watch Changed"

 end

 def change_watch2
 end

 def change_watch3
 end



  # GET /stopwatches/1
  # GET /stopwatches/1.json
  def show
  end

  # GET /stopwatches/new
  def new
    @stopwatch = Stopwatch.new
  end

  # GET /stopwatches/1/edit
  def edit
  end

  # POST /stopwatches
  # POST /stopwatches.json
  def create
    @stopwatch = Stopwatch.new(stopwatch_params)

    respond_to do |format|
      if @stopwatch.save
        format.html { redirect_to @stopwatch, notice: 'Stopwatch was successfully created.' }
        format.json { render :show, status: :created, location: @stopwatch }
      else
        format.html { render :new }
        format.json { render json: @stopwatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stopwatches/1
  # PATCH/PUT /stopwatches/1.json
  def update
    respond_to do |format|
      if @stopwatch.update(stopwatch_params)
        format.html { redirect_to @stopwatch, notice: 'Stopwatch was successfully updated.' }
        format.json { render :show, status: :ok, location: @stopwatch }
      else
        format.html { render :edit }
        format.json { render json: @stopwatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stopwatches/1
  # DELETE /stopwatches/1.json
  def destroy
    @stopwatch.destroy
    respond_to do |format|
      format.html { redirect_to stopwatches_url, notice: 'Stopwatch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stopwatch
      @stopwatch = Stopwatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stopwatch_params
      params.require(:stopwatch).permit(:medicine, :time)
    end
end

healthstopwatchv2/app/helpers/application_helper.rb
module ApplicationHelper
end

healthstopwatchv2/app/helpers/home_helper.rb
module HomeHelper
end

healthstopwatchv2/app/helpers/medicines_helper.rb
module MedicinesHelper
end

healthstopwatchv2/app/helpers/stopwatches_helper.rb
module StopwatchesHelper
end

healthstopwatchv2/app/views/home/index.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1>Health Stopwatch</h1></div>
<a class="btn btn-default" href="/medicines/" role="button">View Medicine List</a>
<a class="btn btn-default" href="/stopwatches/" role="button">Stopwatches</a>

healthstopwatchv2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Healthstopwatchv2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

healthstopwatchv2/app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
<% if @medicine.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

    <ul>
    <% @medicine.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :Name %><br>
  <%= f.text_field :Name %>
</div>

<div class="field">
  <%= f.label :time %><br>
  <%= f.number_field :time %>
</div>
</div>
<div class="actions">

<%= f.submit %>

</div>
</form>


<% end %>

healthstopwatchv2/app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

healthstopwatchv2/app/views/medicines/index.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1>Medicine List</h1></div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.Name %></td>
        <td><%= medicine.time %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Delete', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<a class="btn btn-default" href="/medicines/new" role="button">Add Medicine</a>
<a class="btn btn-default" href="/home/index" role="button">Back</a>

healthstopwatchv2/app/views/medicines/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1>New Medicine</h1></div>
</div>

<%= render 'form' %>

<div>
<a class="btn btn-default" href="/medicines/" role="button">Back</a>
</div>

healthstopwatchv2/app/views/medicines/show.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h3 id="notice"><%= notice %></h3></div>
<p>
  <strong>Name:</strong>
  <%= @medicine.Name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @medicine.time %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<a class="btn btn-default" href="/medicines/" role="button">Back</a>

healthstopwatchv2/app/views/stopwatches/_form.html.erb
<%= form_for(@stopwatch) do |f| %>
  <% if @stopwatch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stopwatch.errors.count, "error") %> prohibited this stopwatch from being saved:</h2>

      <ul>
      <% @stopwatch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :medicine %><br>
    <%= f.text_field :medicine %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  <%  @time_1 = :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

healthstopwatchv2/app/views/stopwatches/edit.html.erb
<h1>Editing Stopwatch</h1>

<%= render 'form' %>

<%= link_to 'Show', @stopwatch %> |
<%= link_to 'Back', stopwatches_path %>

healthstopwatchv2/app/views/stopwatches/index.html.erb
<head>
  <link rel="stylesheet" href="/vendor/assets/stylesheets/flipclock.css">
  <%= include_gon %>
</head>
<body>
    <div class="panel panel-default">
    <div class="panel-heading"><h1>Stopwatch</h1></div>
    <br>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Time</th>

          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>Hydromorphine 2 mg </td>
            <td>60</td>
            <th><button class="start1 btn btn-default">Start</button>
            <button class="stop1 btn btn-default">Stop</button>
            <button class="reset1 btn btn-default">Reset</button></th>
          </tr>
          <tr>
            <td>Oxycodone 5 mg</td>
            <td>30</td>
            <th><button class="start2 btn btn-default">Start</button>
            <button class="stop2 btn btn-default">Stop</button>
            <button class="reset2 btn btn-default">Reset</button></th>
          </tr>
          <tr>
            <td>Tramadol 50 mg</td>
              <td>45</td>
              <th><button class="start3 btn btn-default">Start</button>
              <button class="stop3 btn btn-default">Stop</button>
              <button class="reset3 btn btn-default">Reset</button></th>
          </tr>
      </tbody>
    </table>

<!--CLOCK 1 -->
  <h4><%= @string1 %></h4><br>
  <div class="clock_1">
  <script type="text/javascript">
  var clock1;
  var time = 60*60;

  $(document).ready(function() {

    clock1 = $('.clock_1').FlipClock(time, {
          clockFace: 'MinuteCounter',
          countdown: true,
          autoStart: false,
          callbacks: {
            start: function() {
              $('.message').html('The clock has started!');
            }
          }
      });
      $('.start1').click(function(e) {
        clock1.setTime(time);
        clock1.start();
      });
      $('.stop1').click(function(e) {
        clock1.setTime(0);
      });
      $('.reset1').click(function(e) {
        clock1.setTime(time);
      });
  });
</script></div><br>


<!--CLOCK 2 -->

<h4><%= @string2 %></h4><br>
<div class="clock_2">
<script type="text/javascript">
var clock2;
var time2 = 30*60;

$(document).ready(function() {

  clock2 = $('.clock_2').FlipClock(time2, {
        clockFace: 'MinuteCounter',
        countdown: true,
        autoStart: false,
        callbacks: {
          start: function() {
            $('.message').html('The clock has started!');
          }
        }
    });
    $('.start2').click(function(e) {
      clock2.setTime(time2);
      clock2.start();
    });
    $('.stop2').click(function(e) {
      clock2.setTime(0);
    });
    $('.reset2').click(function(e) {
      clock2.setTime(time2);
    });
});
</script></div><br>


<!--CLOCK 3 -->
<h4><%= @string3 %></h4><br>
<div class="clock_3">
<script type="text/javascript">
var clock3;
var time3 = 45*60;

$(document).ready(function() {

  clock3 = $('.clock_3').FlipClock(time3, {
        clockFace: 'MinuteCounter',
        countdown: true,
        autoStart: false,
        callbacks: {
          start: function() {
            $('.message').html('The clock has started!');
          }
        }
    });
    $('.start3').click(function(e) {
      clock3.setTime(time3);
      clock3.start();
    });
    $('.stop3').click(function(e) {
      clock3.setTime(0);
    });
    $('.reset3').click(function(e) {
      clock3.setTime(time3);
    });
});
</script></div><br>

</div></p>
    <script src="/vendor/assets/javascripts/libs/jquery.js"></script>
        <script src="/vendor/assets/javascripts/flipclock/flipclock.min.js"></script>
    <a class="btn btn-default" href="/home/index" role="button">Back</a>
</body>

healthstopwatchv2/app/views/stopwatches/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1>New Stopwatch</h1></div>

<%= render 'form' %>

<div>
<a class="btn btn-default" href="/stopwatches/" role="button">Back</a>
</div>

healthstopwatchv2/app/views/stopwatches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Medicine:</strong>
  <%= @stopwatch.medicine %>
</p>

<p>
  <strong>Time:</strong>
  <%= @stopwatch.time %>
</p>

<%= link_to 'Edit', edit_stopwatch_path(@stopwatch) %> |
<%= link_to 'Back', stopwatches_path %>